### PR TITLE
In basic score estimator, under Japanese rules, do not count points for stones, add points for captures

### PR DESCRIPTION
**Pull request by pdg137**
Before/after:

image image

This should also fix the issue with wrong Japanese handicap scoring:

https://github.com/online-go/online-go.com/issues/1610

One possible issue is that in games with no territory estimated, there's nothing at all marked on the board:

image

### CODE REVIEW

**Comment by benjaminpjones** [comment]
New CI checks are in!

If it's mostly just prettier errors, you can fix them with

```
npm run prettier
```

**Comment by pdg137** [comment]
Testing some cases in Japanese rules:

All white territory:
image

All black territory:
image

Both have territory and captures:
image

**Comment by pdg137** [comment]
Testing cases in AGA with a 3-stone handicap:

image

image

**Comment by pdg137** [comment]
NZ rules with 25 komi and 4 handicap stones (should not get subtracted from the score):

image

Same thing in Chinese, White gets 4 more points:

image

**Comment by pdg137** [comment]
9 handicap Japanese game:
image

**Comment by anoek** [comment]
Awesome, great work @pdg137 !

**Pull request merged**
